### ISSUE TITLE
UNABLE TO EMBED OPENCHAT BOT ON MY WEBSITE 

### ISSUE THREAD

**Issue by iwilldowonders** [openchatai/OpenChat#10]
HELLO THERE,

I HAVE CREATED CHAT BOT ON OPENCHAT.SO WEBSITE AND IT'S WORKING FINE ON THAT WEBSITE BUT I/M UNABLE TO EMBED IT ON MY WORDPRESS WEBSITE, THE ERROR I/M GETTING IS "OPENCHAT.SO REFUSED TO CONNECT" AM I ONLY FACING THIS ERROR OR OTHER PEOPLE ALSO GETTING SAME ERROR? CAN YOU GUIDE ME HOW CAN I SUCCESSFULLY EMBED CHAT BOT ON MY WORDPRESS WEBSITE?

THANKS FOR ANY SUPPORT

**Comment by gharbat** [comment]
Hey, thanks for reporting this. 

It will be resolved in the coming release 👍🏿

**Comment by JanaayCodes** [comment]
> HELLO THERE,
> 
> I HAVE CREATED CHAT BOT ON OPENCHAT.SO WEBSITE AND IT'S WORKING FINE ON THAT WEBSITE BUT I/M UNABLE TO EMBED IT ON MY WORDPRESS WEBSITE, THE ERROR I/M GETTING IS "OPENCHAT.SO REFUSED TO CONNECT" AM I ONLY FACING THIS ERROR OR OTHER PEOPLE ALSO GETTING SAME ERROR? CAN YOU GUIDE ME HOW CAN I SUCCESSFULLY EMBED CHAT BOT ON MY WORDPRESS WEBSITE?
> 
> THANKS FOR ANY SUPPORT

Why are you yelling?

Please dont use all caps unless its necessary.

thank you.

**Comment by iwilldowonders** [comment]
Thanks for your reply.

I'm sorry,but I'm not yelling at you. My caps lock was on and I kept typing
on my pc. I didn't know that capital letters mean yelling. Sorry for the
inconvenience.


Best Regards,
Raj

**Comment by iwilldowonders** [comment]
> Hey, thanks for reporting this.
> 
> It will be resolved in the coming release 👍🏿

Hello,

it's still not working. When can I embed the chatbot on my website?

Thinks for your reply.

Best Regards,
Raj

**Comment by a798047815** [comment]
Same question. Is it because the openchat server-side configuration does not allow embedding of content in iframes on external sites like mine? Thank a lot.

**Comment by jalel-abbassi** [comment]
I have the same problem, could you please resolve it
