### ISSUE TITLE
NEW CHAT BOTS ON OPENCHAT.SO ARE NOT WORKING

### ISSUE THREAD

**Issue by iwilldowonders** [openchatai/OpenChat#14]
Hello I have created few chatbots on openchat.so but none of them are working. I created two chatbots on 1st june, one with pdf file and another one with website link and both are working fine but unable to embed on my website.

On June 1nd and 3rd I have tried creating another chatbot but platform is not working it seems. It shows that chat bot is live but not giving any information. Keep on saying I'm an AI assistant and I can assist with relevant information I am trained with or something similar. 

I tried using VPN as well but it's not working even if I change my account. Can you check if there are errors?

**Comment by andrewhack** [comment]
Same for me. Tried few minutes ago

**Comment by gharbat** [comment]
Sorry for that.

We got a huge amount of bots creations and our vector DB got fully loaded.
Tonight I will move it to a bigger instance that is capable of handling this amount of load with no problems. 

Will keep you updated.

**Comment by gharbat** [comment]
@andrewhack @iwilldowonders 

Just finished the migration, you should be able to create bots now.

The new DB is bigger and will handle the load, however, note that your old bots will lose it's data sources (you can always create new ones) 

------

@iwilldowonders  Regarding embedding on websites, I am aware of this problem and it is on my pipeline to fix.

**Comment by iwilldowonders** [comment]
> Sorry for that.
> 
> We got a huge amount of bots creations and our vector DB got fully loaded. Tonight I will move it to a bigger instance that is capable of handling this amount of load with no problems.
> 
> Will keep you updated.

Why don't you allow users to delete unwanted chatbots and training data from the platform??🤔

**Comment by iwilldowonders** [comment]
I you also allow people to set default message related to their company name and custom welcome message it would be great and looks 100% professional.

**Comment by iwilldowonders** [comment]
If you allow people to set default welcome message for each bot with their company name and custom welcome message. it would be great and looks 100% professional. Please implement this if possible.

You already added this function partially, but the first ever default message is this: 
"Hello, I'm here to help. What can I do for you today?
(This is for demo purposes only. We only support ~10 questions per minute.)"

and if visitor wishes with hello, or Hi then bot is saying I'm the customer support agent for "example company" sometimes. some times it's not telling anything and asking users to send queries related to the context given. 

Best Regards,
Raj
