### ISSUE TITLE
I can't run by dj_backend_server

### ISSUE THREAD

**Issue by yujun-8848** [openchatai/OpenChat#161]
I want to run openchat by dj_backend_server, i follow guide ,but it's hard to run it ,Can you provide more detailed documentation？
for example, i can deploy it Just like  i deploy backend_server(php) and llm_server(ts).

**Comment by yujun-8848** [comment]
if i exec `make install`, it will display `make: *** No rule to make target `.env', needed by `install'.  Stop.`

**Comment by codebanesr** [comment]
It's possible that you're not currently located in the correct directory, or you might be missing the necessary .env file. Alternatively, you can launch the image using docker-compose, depending on your system's architecture:
- For Linux, execute `docker-compose -f docker-compose.linux.yaml`.
- If you're on macOS, run `docker-compose up -d`.

**Comment by yujun-8848** [comment]
I pull `main` branch.
cd 'dj_backend_server/'
 it only have `example.env.docker`,i can copy `example.env.docker` rename it `.env.docker`, I see it by makefile.but it don't have '.env'  or `.env.example`.
makefile: `install: .env install-requirements docker-compose up -d` 
Can you provide more detailed documentation about .env？ I'm troubled about it. @codebanesr
