### ISSUE TITLE
django.db.utils.ProgrammingError: (1146, "Table 'openchat.auth_user' doesn't exist")

### ISSUE THREAD

**Issue by zhongchongan** [openchatai/OpenChat#182]
Where is the mysql database initialization script?

**Comment by zhongchongan** [comment]
![image](https://github.com/openchatai/OpenChat/assets/87646634/f5bda530-8337-4ba2-8de2-068c0f16ed4a)
@codebanesr How to configure this request address?
Now the request from the web page is always 0.0.0.0

**Comment by lvalics** [comment]
It will be fixed in the next version soon ....
