### ISSUE TITLE
search.js has errors

### ISSUE THREAD

**Issue by iOSDevSK** [openchatai/OpenChat#190]
Where I can find the source code of search.js? Is it opensource? 
What is this in search.js?  

Ui.post("/81345265-dbf5-4c7e-ae0b-ff325e324c0d", E);
And also this?

 const E = { message_id: r, is_good: m };
 Ui.post("/81345265-dbf5-4c7e-ae0b-ff325e324c0d", E);

**Comment by iOSDevSK** [comment]
And Ui.get ? Ui.get("/58fc397f-00d2-47f4-95a7-e9bc93de98ab")

This seems to be hardcoded and won't work.

**Comment by lvalics** [comment]
Fixed in the entrypoint. Will be pushed later to main.
