### ISSUE TITLE
Is there a way to change the OpenAI API base URL [local llm] 

### ISSUE THREAD

**Issue by databill86** [openchatai/OpenChat#197]
Hello, 

There are a lot of OpenAI-compatible RESTful APIs. [Fastchat](https://github.com/lm-sys/FastChat/tree/main) is a good example, it's an open platform for serving a large open source llms. 
Because it's compatible with openAI API, it makes it very easy to switch between openAI models and open source ll models. The only parameters to change are:
```
openai.api_key = "EMPTY"
openai.api_base = "http://localhost:8008/v1"
```
Is there a way we can do this in OpenChat ? 

[Edit]: I came across this: https://github.com/openchatai/OpenChat/blob/main/dj_backend_server/readme.md#environment-variables-in-the-env-file 
It seems that we can do that by changing the env variable in the django backend server. But, `OPENAI_API_BASE` is not used at all in `dj_backend_server`. 
We only use `AZURE_OPENAI_API_BASE` (eg., in `get_azure_openai_llm()` `openai_api_base=os.environ['AZURE_OPENAI_API_BASE']`)

Is there a way to make that possible ?

**Comment by codebanesr** [comment]
Of all the options, I think Ollama is the most straightforward. By setting the IP address for chat models to 'host.docker.internal', we can enable the docker containers to communicate with Ollama on the host machine. 

Ollama: https://ollama.ai/

You can find the implementation here

https://github.com/openchatai/OpenCopilot/blob/main/llm-server/utils/get_chat_model.py
