### ISSUE TITLE
no connection to qdrant 

### ISSUE THREAD

**Issue by JuergenCornely** [openchatai/OpenChat#198]
llm servers tries to reach qdrant at 127.0.1.1 and thast not reachable. qdarant ist reachbale from 127.0.0.1 how to change the ip?

**Comment by lvalics** [comment]
# if using qdrant
QDRANT_URL=http://qdrant:6333

it is defined in .env.docker

**Comment by JuergenCornely** [comment]
Thats where i had placed it.  But i had given a name instead of IP.. Know it works with IP Adress correctly
