### ISSUE TITLE
Post requests to some website [https://chat.ghidulprimariilor.ro/api/chat/send/] 

### ISSUE THREAD

**Issue by databill86** [openchatai/OpenChat#199]
Hello, 
After installed the django backend on docker, and creating a chatbot on some crawled website, I couldn't get the bot to chat. 
Requests are being sent to some website [https://chat.ghidulprimariilor.ro/api/chat/send/
](https://chat.ghidulprimariilor.ro/api/chat/send/
)
Is there a reason for this ? 

![image](https://github.com/openchatai/OpenChat/assets/41125230/c3a3e20e-8fe6-4c3a-a706-679cdee12583)

Edit: It seems that the changes to `dj_backend_server/web/static/chat.js` related to this are made by @lvalics in this pull: https://github.com/openchatai/OpenChat/pull/193

**Comment by lvalics** [comment]
No, there is a wrong JS. You need to replace in JS with your domain. I will tell to the guys to fix the JS.

**Comment by lvalics** [comment]
Check the updated version.
