### ISSUE TITLE
Pricing page is down

### ISSUE THREAD

**Issue by tpmccallum** [openchatai/OpenChat#204]
https://openchat.so/pricing

<img width="1724" alt="Screenshot 2023-11-20 at 13 58 40" src="https://github.com/openchatai/OpenChat/assets/9831342/8e470805-c7db-4fe6-abe8-0bd153e040f8">

**Comment by codebanesr** [comment]
@tpmccallum This is intentional. we will be moving almost all of openchat feature to opencopilot and then bring back the pricing page.
