### ISSUE TITLE
Embedded Chat Bubble

### ISSUE THREAD

**Issue by JuergenCornely** [openchatai/OpenChat#210]
I whant to have a direct chat function like it s shown in the Video. But on my site i ve to click first on the "ask our bot" field. How can i change it?

**Comment by kientv** [comment]
Me too

**Comment by codebanesr** [comment]
@kientv @JuergenCornely you might want to check https://github.com/openchatai/OpenCopilot, it comes with it's own sdk too, so you can create copilots programmatically
