### ISSUE TITLE
dj backend csfr error

### ISSUE THREAD

**Issue by JuergenCornely** [openchatai/OpenChat#212]
I try to use the new django. I  got it installed, but when i try to conect i got a CSRF verification error from Django.. any hints for me

**Comment by codebanesr** [comment]
You should add the origin in settings.py file

**Comment by codebanesr** [comment]
If allowed hosts is not defined in .env, it should be listening on
0.0.0.0:8000 by default

**Comment by codebanesr** [comment]
Please update .env with the following and restart your containers
```
ALLOWED_HOSTS=localhost,0.0.0.0
APP_URL=http://0.0.0.0:8000
```

then navigate to `http://0.0.0.0:8001/login`

Default admin user
user - admin
password - admin_password

**Comment by JuergenCornely** [comment]
Same problem, i get the login Page. After pressing the login button i got the CSFR verification failed

**Comment by JuergenCornely** [comment]
in my envoirment the makefile at the force_migrate section goes to the docker Container web. But the installtion makes a container oc_web.. hope this can help

**Comment by lvalics** [comment]
Temporarelly you can bypass in settings.py
# 'django.middleware.csrf.CsrfViewMiddleware',

**Comment by lvalics** [comment]
Can you check now please? Get the latest release.

**Comment by JuergenCornely** [comment]
It works,  thanks a lot...
