### ISSUE TITLE
latest django &mysql

### ISSUE THREAD

**Issue by JuergenCornely** [openchatai/OpenChat#217]
With the latest version i run into a error: "djang.db.utils.OperationalError cant connect to MySQL on mysql.

With the adminer i can connect to the database..

Some hints for me?

**Comment by JuergenCornely** [comment]
if i set the SQL Servername at the env file to localhost my oc_web container sdtops working..

**Comment by codebanesr** [comment]
when running inside docker, the server name will be the same as container name in dockerfile. Please go through this readme once, it should answer your question
https://github.com/openchatai/OpenChat/tree/main/dj_backend_server

**Comment by codebanesr** [comment]
Hey @JuergenCornely 
use the following: `docker compose -f docker-compose.linux.yaml up -d --build --no-deps web`
after make install

just a quick fix... i will push a fix to main soon

**Comment by codebanesr** [comment]
now you can do the following
> cd dj_backend_server
> make pre-install
> make install

**Comment by JuergenCornely** [comment]
i ll try and give feedback

**Comment by JuergenCornely** [comment]
i tried oc_web is up and running again. Adminer can connect to sql database but backend lists error
![image](https://github.com/openchatai/OpenChat/assets/117660389/2a2e1749-c2b2-4c93-b255-e2feffb94790)

**Comment by lvalics** [comment]
Normally python depend on MySQL, is mandatory to wait to start, but seems sometimes mySQL send a message that started but is not yet finished. I think this is why you get and finally the site will work. Confirm please if the site is working after a while or just the adminer.

**Comment by JuergenCornely** [comment]
Confirmed

**Comment by JuergenCornely** [comment]
Thanks a lot for the very quick support
