### ISSUE TITLE
dj_backend missing the example.env file

### ISSUE THREAD

**Issue by JuergenCornely** [openchatai/OpenChat#225]
by the latest release i m missing the example.env file

**Comment by lvalics** [comment]
# "azure" | "openai" | llama2
OPENAI_API_TYPE=openai
OPENAI_API_MODEL=gpt-3.5-turbo
OPENAI_API_TEMPERATURE=1

# If using azure
# AZURE_OPENAI_API_BASE=
# AZURE_OPENAI_API_KEY=
# AZURE_OPENAI_API_VERSION=2023-03-15-preview
# AZURE_OPENAI_EMBEDDING_MODEL_NAME=
# AZURE_OPENAI_DEPLOYMENT_NAME=
# AZURE_OPENAI_COMPLETION_MODEL=gpt-35-turbo


# For openai
OPENAI_API_KEY=



# "azure" | "openai" | llama2
EMBEDDING_PROVIDER=openai

# Vector Store, PINECONE|QDRANT
STORE=QDRANT


# if using pinecone
# PINECONE_API_KEY=
# PINECONE_ENV=
# VECTOR_STORE_INDEX_NAME=


# if using qdrant
QDRANT_URL=http://qdrant:6333


# optional, defaults to 15
MAX_PAGES_CRAWL=15

# --- these will change if you decide to start testing the software
CELERY_BROKER_URL=redis://redis:6379/0
CELERY_RESULT_BACKEND=redis://redis:6379/0
DATABASE_NAME=openchat
DATABASE_USER=dbuser
DATABASE_PASSWORD=dbpass
DATABASE_HOST=mysql
DATABASE_PORT=3306

# retrieval_qa | conversation_retrieval, retrieval_qa works better with azure openai

# Add Allowed Hosts here, no quote, just IP or domain, separated by a comma
ALLOWED_HOSTS=localhost,0.0.0.0
APP_URL=http://0.0.0.0:8000

# use 'external' if you want to use below services.
PDF_LIBRARY = 'internal'

#PDF API - OCRWebService.com (REST API). https://www.ocrwebservice.com/api/restguide
#Extract text from scanned images and PDF documents and convert into editable formats.
#Please create new account with ocrwebservice.com via http://www.ocrwebservice.com/account/signup and get license code
OCR_LICCODE = 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX'
OCR_USERNAME =  'username'
OCR_LANGUAGE = 'english'
# Advantage to clean up the OCR text which can be messy and full with garbage, but will generate a cost with LLM if is paid. Use carefully.
# Use 1 to enable, 0 to disable.
OCR_LLM = 0

# Replace in Chat JS and Search JS english language strings with these (use your own language)
LNG_BOT='Bot is Thinking...'
LNG_ERROR='Error sending the message.'
LNG_WRITE='Ask a question...'
LNG_ASK='Write a reply...'

**Comment by lvalics** [comment]
We will check why was deleted, happens, probabbly when it was renamed from example.env.docker
