### ISSUE TITLE
django backend Problem

### ISSUE THREAD

**Issue by JuergenCornely** [openchatai/OpenChat#228]
I have  Problems after setting up django backend via https.

1) If i set up the App URL with "http://myserver.com:8000" at the env file the system tells me "There was Problem while training 
       my bot with  PDF"
    
      If I set up with App URL "0.0.0.0"  the Training of the uploaded PDF works.

2) At both cases if i ask the bot a qusetion i ll get Error sending message.

Error: 
chat.js?v6:69 Mixed Content: The page at 'https://myserver/chat/b50a7e1e-e683-446e-9/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://myserver:8000/api/chat/send/'. This request has been blocked; the content must be served over HTTPS.

I had done  setup the env.docker with the names of the docker container like: oc_mysql, oc_qdrant...   

Start Page, Chat Page , Adminer Page is working fine...

I dont know where my mistake is, but i believe at the setup of the nginx Conf? could anyony give me a Idea how to fix this...

**Comment by JuergenCornely** [comment]
Anyone here hints for me? or can send me a working nginx.conf?

**Comment by JuergenCornely** [comment]
Hi all, after some hours i believe i had the most .. https is working for the dashbord and the Chat client https view.

if i send a quetion a get the folling error at the log:

oc_web           |   File "/usr/local/lib/python3.9/site-packages/qdrant_client/qdrant_client.py", line 340, in search
oc_web           |     return self._client.search(
oc_web           |   File "/usr/local/lib/python3.9/site-packages/qdrant_client/qdrant_remote.py", line 437, in search
oc_web           |     res: grpc.SearchResponse = self.grpc_points.Search(
oc_web           |   File "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 1030, in __call__
oc_web           |     return _end_unary_response_blocking(state, call, False, None)
oc_web           |   File "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 910, in _end_unary_response_blocking
oc_web           |     raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
oc_web           | grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
oc_web           |      status = StatusCode.UNAVAILABLE
oc_web           |      details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:172.31.0.3:6334: Ssl handshake failed: SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER"
oc_web           |      debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:172.31.0.3:6334: Ssl handshake failed: SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER {grpc_status:14, created_time:"2024-01-19T08:53:24.374247813+00:00"}"
oc_web           | >
oc_web           |
oc_web           | Internal Server Error: /api/chat/
oc_web           | 'text'
oc_web           | Traceback (most recent call last):
oc_web           |   File "/app/api/views/views_message.py", line 226, in send_chat
oc_web           |     "text": bot_response.get_bot_reply()
oc_web           |   File "/app/api/views/views_message.py", line 38, in get_bot_reply
oc_web           |     return self.response['text']
oc_web           | KeyError: 'text'
oc_web           | [19/Jan/2024 08:53:24] "POST /api/chat/ HTTP/1.1" 500 30
oc_web           | Internal Server Error: /api/chat/send/

Could anyone give me a hint what i ve to do?

**Comment by lvalics** [comment]
is best always to work with https://  but normally nginx will do the upstream in http:// internally.

**Comment by JuergenCornely** [comment]
Thats my problem i believe ... It does not work as a reverse Proxy. it only forward as http... Im working to understand nginx...

**Comment by lvalics** [comment]
Today it was pushed a version, huge updates, but maybe with this will work?

**Comment by JuergenCornely** [comment]
I have seen it.. i ll try and give you a feedback.

**Comment by JuergenCornely** [comment]
After making a complete reinstall with the latest patch and editing the at the dockercompose .yaml  the ports for the Webcontainer from 8001:8000 to 8000:8000 it works....

Many thanks for the support...
