### ISSUE TITLE
django backend latest release

### ISSUE THREAD

**Issue by JuergenCornely** [openchatai/OpenChat#231]
At the latest dj-backend there seems to be a bug at adding a new source by editing a existing Bot..
And the share link starts the embeded webapp bubble on a blank page

**Comment by lvalics** [comment]
"At the latest dj-backend there seems to be a bug at adding a new source by editing a existing Bot.." I pushed today some fix, could be fixed. Put some screenshoot to see what is the issue.

"And the share link starts the embeded webapp bubble on a blank page"
Yeah, I saw it and even if is used fullScreen is not. But is fixed on mobile to show it ok. Normally bubble chat need to be bubble chat, but I will investigate wht fullScreen is not working.

**Comment by JuergenCornely** [comment]
At the latest dj-backend there seems to be a bug at adding a new source by editing a existing Bot.." I pushed today some fix, could be fixed. Put some screenshoot to see what is the issue.

For this it is working with the latest update.......

**Comment by lvalics** [comment]
it was a push today, check that.

**Comment by JuergenCornely** [comment]
git says 17 hours ago..  i ll wait ..

But only one is left:

And the share link starts the embeded webapp bubble on a blank page"
Yeah, I saw it and even if is used fullScreen is not. But is fixed on mobile to show it ok. Normally bubble chat need to be bubble chat, but I will investigate wht fullScreen is not working.

**Comment by lvalics** [comment]
<img width="666" alt="image" src="https://github.com/openchatai/OpenChat/assets/27447535/6e792dee-8212-410e-8853-995c41d16809">

**Comment by JuergenCornely** [comment]
Same behvior for the chatbot user Page..

**Comment by lvalics** [comment]
Can I see some screenshoot?

**Comment by JuergenCornely** [comment]
Start Page from the current Version of the Chat Page:
![aktuell](https://github.com/openchatai/OpenChat/assets/117660389/0b64ded4-5327-465a-9ed9-a1a20dc31ed9)

**Comment by JuergenCornely** [comment]
From the prevoius Verions:

![image](https://github.com/openchatai/OpenChat/assets/117660389/274968c5-8a94-4e99-918a-3d7d280c928c)

**Comment by lvalics** [comment]
Yes, I know this, I think it is something related with chat.js version. I will check when I have some time.

**Comment by JuergenCornely** [comment]
Thanks a lot for your very good supprot.
 should i close this Issue?

**Comment by lvalics** [comment]
You can close, or can be open until we will fix.

**Comment by lvalics** [comment]
<img width="329" alt="image" src="https://github.com/openchatai/OpenChat/assets/27447535/c4b9280a-940d-4e2a-bfbb-418dbc466232">
Fixed, will be approved soon.

**Comment by lvalics** [comment]
Check it now.

**Comment by JuergenCornely** [comment]
Works... Great Job
