### ISSUE TITLE
Adding new Data Source (PDF) and can't download. It shows 404

### ISSUE THREAD

**Issue by rsalbarico** [openchatai/OpenChat#234]
I attempted to "Add a new data source" in the "Data & Knowledge" section and upload a PDF. It successfully saves under app > shared_data > folder_name [dynamic id] > files [*.pdf]. However, when I try to download it, I get a 404 error. The URL format provided by the download button is:
http://localhost:8000/app/chatbot_id/files
http://localhost:8000/app/8e6ac821-27a0-4a35-95c8-228dcbe74e58/FxlcrUHroXxgFjL1yrwI.pdf

What could be the problem? An I missing something in the setup?

![image](https://github.com/openchatai/OpenChat/assets/2360770/13e41044-961d-4809-9dbe-5b3d512bdbcd)
![image](https://github.com/openchatai/OpenChat/assets/2360770/f297b9a3-e0ca-4a0b-ac01-6c44ae650d58)

**Comment by lvalics** [comment]
The PDF link is not OK. There is 2 things to verify
- if you did not choosed to be deleted after uploaded.
- it should be in website_data_sources/SOMENUMBERHERE/ directory.
