### ISSUE TITLE
 Webapp Searchbox

### ISSUE THREAD

**Issue by JuergenCornely** [openchatai/OpenChat#235]
ad the latest django Version there is a problem with the web app serch box..

At The search js there is a wron url places for the system ( anyting wit .ro) i ve edit hte field with the right Servername.
The search Box opens coreect ic can write a question but the Bot cant answer. No error message is displayed. At devtools i can see:
Failed to load resource: the server responded with a status of 404 ()

**Comment by lvalics** [comment]
I worked in the search but I donțt think it was yet made a push. I hope will work.
The URL is hardcoded in search.js, I changed now to be default http://0.0.0.0:8000 but aslyou you can overwrite from JS script. Example here: https://victoury.be/1.html

**Comment by JuergenCornely** [comment]
Thanks
 i ll wait @

**Comment by lvalics** [comment]
Yeah, I found the issues, It was pushed the hardocoded version. Edit the search.js temporary look for baseURL:"https://____ /api"} and change it.

**Comment by JuergenCornely** [comment]
if changed the base URL  from https://myserver.mydom.de/api. to: http://0.0.0.0:8000/ without succsess. At hte Chat,js it works with this config..

Ill fetch the search from the hardcoded Version a try it..

**Comment by lvalics** [comment]
You need to change in search.js the baseURL:"https:// and the URL from there change it to your URL,  https://myserver.mydom.de/ and will work. The next version will not need anymore the URL from inside. It will be controlled from JavaScript.

**Comment by JuergenCornely** [comment]
no that doesnt work it tried it..  Axios Error 404

**Comment by JuergenCornely** [comment]
i think i ve to wait for the next version

**Comment by lvalics** [comment]
Maybe the guys will have time today to push the new version and I hope you will like it.

**Comment by JuergenCornely** [comment]
By the way you all do a very great Job here. And it is very great what this tool can do!!!!!

**Comment by lvalics** [comment]
You have a showcase ? We would like to know where people are using the software.

**Comment by JuergenCornely** [comment]
I ll make some features public so youn can acsses it. For the Integration in on of our Plattfor if mad ill send you a Video.. Ill tri it tomorrow

**Comment by lvalics** [comment]
Update was merged.

**Comment by JuergenCornely** [comment]
![image](https://github.com/openchatai/OpenChat/assets/117660389/565d54b4-f853-4dde-a807-2a330a40eba2)
Key Error with secrety Key?

**Comment by lvalics** [comment]
In your .env add a line

SECRET_KEY='yourkey here to be secret.'

**Comment by JuergenCornely** [comment]
That was the hint that i need. Can confirm that it is working.... Thanks a lot @lvalics...........

**Comment by JuergenCornely** [comment]
Here are to Short Videos about my internal Testintegration for

https://github.com/openchatai/OpenChat/assets/117660389/b6c196fc-ad2b-4067-beee-2a2c1ceef761


https://github.com/openchatai/OpenChat/assets/117660389/493552a5-303f-48f7-9f48-1747ff4ab5b5

 Openchat

**Comment by JuergenCornely** [comment]
i got it with the latest update this week, but i made teh Video before.... By the way i ve another Quetion:

I ve made a integration lonnger time ago into another Software not Based on Openchat where i send a axios request to Openai to get a answer .. Can i acsess Openchat via axios to ask the system and get a answer ?

**Comment by lvalics** [comment]
I do not have knowledge in axios, so I cannot help you on this. Sorry.

**Comment by JuergenCornely** [comment]
It s okay axios isnt the problem i dont know how i can connect with openchat api from external system..

**Comment by lvalics** [comment]
https://yourdomain.com/api/chat/ etc, check api/urls.py for API part. I am working on this to do it easier to understand it.
Also try in browser, /api/schema/swagger-ui/  /api/schema/redoc/

**Comment by lvalics** [comment]
Partially. Still need to add all the endpoints, but had no time yet. So if you add, let me know, we will merge it.
