### ISSUE TITLE
NextJS for Server, great! But PHP! WHAT?!?

### ISSUE THREAD

**Issue by strangelearning** [openchatai/OpenChat#28]
Is this some sort of "obfuscation" by "mature tech usage" scheme?!?! 🤪

Would love if this was all in NextJS.

Just curious on the devs choice of PHP!

**Comment by rendao** [comment]
php for web service is ok, i think it is  convenient and efficient. And, the core is llm-server in this project.

**Comment by gharbat** [comment]
Hey, PHP only used on the backend-server side, not llm-server, it should be straight forward to get onboard (standard Laravel MVC), yet the project is still new, and I am open to re-write the backend server in a different stack, do you have any thing on mind?

**Comment by nhenderson** [comment]
Laravel is great! Don't change it :+1:

**Comment by strangelearning** [comment]
Maybe I should learn Laravel! I have heard great things. Just confused me initially seeing both NextJS and PHP is all. No negativity towards devs at all!
