### ISSUE TITLE
Is the 5 PDFs/100k words limit a technical limitation?

### ISSUE THREAD

**Issue by bryceamacker** [openchatai/OpenChat#3]
Just wanted to check if that limit is more of a recommendation for the online demo to save on costs, or if there is a technical reason to limit ingestion to that amount. Thank you for building this, it looks like a great product!

**Comment by gharbat** [comment]
Indeed it's more of a recommendation for the online demo.

You should be able to ingest bigger files (it depend also on your vector database) with no problems.

Also if you have particular use case with large files, I would love to hear about it!

Cheers!

**Comment by gharbat** [comment]
It's demo limitation, actually, the self hosted version does not have any limitations (maybe the language is not accurate - will change that)

cheers!

**Comment by bryceamacker** [comment]
I'm actually adding a local vector store (chroma) and was wondering if that was something you guys discovered during development. I'll submit a PR once I'm happy with it if you are interested.
