### ISSUE TITLE
OpenestChat

### ISSUE THREAD

**Issue by rodfer0x80** [openchatai/OpenChat#39]
I would like to see a fork where we could run our own custom llama/or w/e model locally instead of being API dependent on a massive private corp

**Comment by gharbat** [comment]
I'm working on adding opensource LLM model + open source vector DB in the coming releases, so OpenChat will operate 100% offline, at the end, this the product's vision XD

**Comment by EhabAmawi** [comment]
@gharbat 
Checkout [this repo](https://github.com/h2oai/h2ogpt), I think it's a great alternative to chatGPT API
