### ISSUE TITLE
Failed to initialize Pinecone Client

### ISSUE THREAD

**Issue by koala73** [openchatai/OpenChat#5]
It shows as processed in the UI:

<img width="285" alt="CleanShot 2023-06-01 at 14 07 05@2x" src="https://github.com/openchatai/OpenChat/assets/996596/2b5e8fc9-03c2-467f-91ca-661b93293c47">

but that's what I see in logs

<img width="925" alt="CleanShot 2023-06-01 at 14 07 20@2x" src="https://github.com/openchatai/OpenChat/assets/996596/74f99e54-f7d3-4593-b306-8636bbab64b8">

**Comment by eduardosantosjr** [comment]
https://github.com/openchatai/OpenChat/issues/8#issuecomment-1572923256

:)
