### ISSUE TITLE
About your project - open sourcing

### ISSUE THREAD

**Issue by Antazia** [openchatai/OpenChat#73]
Hi.

I'm wondering about your roadmap, will the features : analytics, file deleting & re-syncing, UI designer etc... become open source or it will only be listed on openchat.so?

Thank you, I need some clarification about this.

**Comment by gharbat** [comment]
Hey,

Most of the features will end up open sourced (some of them will remain closed source, but only few), usually I release new feature on the website (openchat.so) before merging them on the open sourced version (~1 week before), I do that to see the adoption rate and to do some A/B testing.
