### ISSUE TITLE
How to support multiple languages

### ISSUE THREAD

**Issue by cidrugHug8** [openchatai/OpenChat#9]
Hi there,
gpt-3.5-turbo and others can handle non-English languages. Currently OpenChat is only in English, right? Can you please support multi languages?

**Comment by gharbat** [comment]
It's on my road map, but it should be relatively easy to support any language by changing the initial prompt.
you can join our discord server  https://discord.gg/yjEgCgvefr so you know when we release this feature. 

cheers.

**Comment by cidrugHug8** [comment]
I was able to modify the prompt to support multiple languages. The response is slow and the screen does not refresh. Could you please make it possible to set a timeout?
